# Generated by Django 5.2.7 on 2025-10-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plants_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
