# Generated by Django 5.2.7 on 2025-11-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plants_latitude_plants_location_plants_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='location',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='longitude',
        ),
    ]
