# Generated by Django 5.2.7 on 2025-11-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_plants_latitude_remove_plants_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
