# Generated by Django 5.2.7 on 2025-10-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_piture',
            new_name='profile_picture',
        ),
    ]
