# Generated by Django 5.2.7 on 2025-10-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_profile_piture_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('plant_owner', 'Plant Owner'), ('seller', 'Seller')], default='plant_owner', max_length=20),
        ),
    ]
