# Generated by Django 5.2.7 on 2025-12-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionresult",
            name="groq_raw_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
