# Generated by Django 5.2.7 on 2025-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_watering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantwatering',
            options={'ordering': ['-watering_date']},
        ),
        migrations.RemoveField(
            model_name='plantwatering',
            name='user',
        ),
        migrations.AddField(
            model_name='plantwatering',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantwatering',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plantwatering',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
