# Generated by Django 5.2.7 on 2025-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_watering', '0002_remove_plantwatering_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantwatering',
            name='next_watering_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
