# Generated by Django 5.2.7 on 2025-11-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_watering', '0002_alter_plantwatering_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantwatering',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='plantwatering',
            name='location',
        ),
        migrations.RemoveField(
            model_name='plantwatering',
            name='longitude',
        ),
    ]
